import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
	// const { data, isLoading } = trpc.useQuery([
	// 	'example.hello',
	// 	{ text: 'from tRPC' },
	// ]);
	const { data, isLoading } = trpc.useQuery(['star.getAll']);

	return (
		<div className={styles.container}>
			<Head>
				<title>Chem Eng</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<main className={styles.main}>
					<h1 className={styles.title}>Hello</h1>

					<div className={styles.linksContainer}>
						<h2>Links</h2>
						<Link href="/GasConvert">
							<a className={styles.link}>Gas conversion</a>
						</Link>
						<Link href="/GasConvert">
							<a className={styles.link}>Other information</a>
						</Link>
						<Link href="/GasConvert">
							<a className={styles.link}>Something else</a>
						</Link>
					</div>
					{data ? (
						<p>{`Database Test: ${data[0]?.name} ${data[0]?.constellation}`}</p>
					) : (
						<p>Database Test: Loading..</p>
					)}
					{/* <a href="/GasConvert" target="_blank" rel="noreferrer">
						TypeScript
					</a> */}
				</main>
			</div>
		</div>
	);
};

export default Home;
